services:
  - type: web
    name: cfg-comparison-app
    env: python
    buildCommand: pip install -r requirements-production.txt
    startCommand: gunicorn --chdir webapp --bind 0.0.0.0:$PORT --timeout 120 --workers 2 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production

