services:
  - type: web
    name: cfg-comparison-app
    env: python
    buildCommand: pip install -r requirements-production.txt
    startCommand: cd webapp && gunicorn app:app --timeout 120 --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
    disk:
      name: uploads
      mountPath: /opt/render/project/src/webapp/uploads
      sizeGB: 1
